version: '3'

networks:
  laravue:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: "laravue-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravue
  mysql:
    image: mysql:5.7.22
    container_name: "laravue-mysql"
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
      SERVICE_TAGS: 'dev'
      SERVICE_NAME: 'mysql'
    networks:
      - laravue
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "laravue-php"
    volumes:
      - ./src:/var/www
    ports:
      - 9000:9000
    networks:
      - laravue